### PR TITLE
Automatically install modules (No more npm install)

### PR DESCRIPTION
**Pull request by Andrews54757**
1. Auto-module installer
2. Efficiency
3. Fixes
4. Update Packets for new client (Not done yet)

### CODE REVIEW

**Comment by LegitSoulja** [comment]
Hm, @Andrews54757 do you have thoughts on how you want the client to be setup/start off exactly? Would you like to start it off? I don't know much about pc yet, but the api is huge.

I was going to use requirejs, just to git rid of confusing writing in one file (Since I write classes ALOT), and everything will be compiled together afterwards.

**Comment by LegitSoulja** [comment]
@Andrews54757 @SharkFinPro check gitter

**Comment by SharkFinPro** [comment]
k

**Comment by LegitSoulja** [comment]
- Update domain (We no longer own ogarul.io)
- Decrease the time of the update requests of OAStats (Recommemded, 1E3*10)

**Comment by LegitSoulja** [comment]
Make sure you re-check all requests, (The API system may been defective). Until updated (Slick Inject). I'll have that finish/implemented today.

**Comment by LegitSoulja** [comment]
Also we can't make updates to the  server as of now, as  I'm planning on migrating servers/host. Lets get everything done and released. Make it the first official release.

**Comment by threeheadedgoose** [comment]
i don't understand anything here

**Comment by LegitSoulja** [comment]
@threeheadedgoose sorry, but **OpenAgar** discontinued because of inactivity, hosting changes, and my lack of care in the **Agario** community as it has became pathetic. I decided to leave this community and focus on my real life.

There hasn't been news if **OpenAgar** will ever continue, but just know that we still have copies, and could bring it up at any time, but is it worth it? 

Everything is in the hand's of @Andrews54757. It'll be his decision on what he carry out for this project. He could keep it and do something big, or just give up all the work/time of this project. (His first full project). 

I hope things goes well, but I hope you understand, and I finally wrote this post.

Farewell,
@MichaelLeeHobbs 
@Andrews54757 
@SharkFinPro

**Pull request merged**
